### ISSUE TITLE
Images aren't scaled with bigger screens

### ISSUE THREAD

**Issue by DylanVanAssche** [walokra/sailimgur#18]
When you click on a image the image is very small on bigger screen. This can be fixed by using the Screen.width and Screen.height property in QML when defining the size of the image.

**Comment by walokra** [comment]
Thanks for reporting this. The images in gallery are fetched as scaled (640x640 preserving aspect ratio) as it's the resolution in Jolla phone and if it's Jolla Tablet the images are fetched as original. That's done for performance reasons. So, the issue is with other phones running Sailfish OS with bigger screens.

For now, you can long press the image to see action buttons and open the original image.

I could add setting for getting original images (or in bigger scale) in albums which should resolve the issue. Not sure when I have time to do this.

**Comment by modulebaan** [comment]
I will try it out and send you a pull request?

**Comment by walokra** [comment]
Of course PR is welcome :)

**Comment by modulebaan** [comment]
I tried to build it but it seems that I don't have an API key or something.
I just need to see an image to try it out...

_QT console log:_
```
[D] tryRefreshingTokens:142 - Permission denied. Trying to refresh tokens.
[D] showHttpError:96 - API error: code=400; message=Bad Request: Client id was not found in the headers or body. Can't refresh tokens. Please sign in again.
```

**Comment by walokra** [comment]
You can get the OAuth2 tokens from https://api.imgur.com/oauth2.

**Comment by henk84** [comment]
AFAICT this issue is not correct for the latest version (I’m on the newest build for aarch64, if that is important). I’d assume it can be closed.
